name: BlockShufflePlugin
author: Xorinzor 
description: A modified version of the BlockShuffle plugin by SulphurousC
commands:
  blockshuffle:
    description: BlockShuffle Main Command
    usage: "Usage : /blockshuffle [start][stop][info][add][remove][list][set [RoundTime][foodAmount]]"
version: 1
main: com.xorinzor.blockshuffle.Main
api-version: 1.16
depend: [MVdWPlaceholderAPI]